name: Build

on:
  push:
    branches: [develop,main]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [develop,main]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x, 19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build